#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'MotionDetectorMsg'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 1

# The Active Message type associated with this message.
AM_TYPE = 6

class MotionDetectorMsg(tinyos.message.Message.Message):
    # Create a new MotionDetectorMsg of size 1.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=1):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <MotionDetectorMsg> \n"
        try:
            s += "  [payload=0x%x]\n" % (self.get_payload())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: payload
    #   Field type: short
    #   Offset (bits): 0
    #   Size (bits): 8
    #

    #
    # Return whether the field 'payload' is signed (False).
    #
    def isSigned_payload(self):
        return False
    
    #
    # Return whether the field 'payload' is an array (False).
    #
    def isArray_payload(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'payload'
    #
    def offset_payload(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'payload'
    #
    def offsetBits_payload(self):
        return 0
    
    #
    # Return the value (as a short) of the field 'payload'
    #
    def get_payload(self):
        return self.getUIntElement(self.offsetBits_payload(), 8, 1)
    
    #
    # Set the value of the field 'payload'
    #
    def set_payload(self, value):
        self.setUIntElement(self.offsetBits_payload(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'payload'
    #
    def size_payload(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'payload'
    #
    def sizeBits_payload(self):
        return 8
    
